"use client";

import { Button } from '@/components/ui/button'
import {
    ArrowLeft, Check, CheckCircle2
} from 'lucide-react'
import Image from 'next/image'
import Link from 'next/link'
import React, { useEffect, useState } from 'react'
import { Card } from '@/components/ui/card'
import { useSearchParams } from "next/navigation";

export default function ScanResult() { 

    const searchParams = useSearchParams();
    const dataParam = searchParams.get("data");

    const [formattedDate, setFormattedDate] = useState<string>("");

    let scanData: any = null;

    try {
        if (dataParam) {
            scanData = JSON.parse(decodeURIComponent(dataParam));
        }
    } catch (e) {
        console.error("Error parsing data", e);
    }

    const scan = scanData?.data?.scan;

    useEffect(() => {
        if (scan?.createdAt) {
            const date = new Date(scan.createdAt).toLocaleDateString('en-GB', {
                year: 'numeric',
                month: 'long',
                day: 'numeric'
            });
            setFormattedDate(date);
        }
    }, [scan?.createdAt]);

    return (
        <div className="min-h-screen bg-[#F6F6F8] p-6">

            <div className="relative flex justify-between max-w-5xl mx-auto mb-16 px-4">
                <div className="absolute top-4 left-0 w-full h-0.5 bg-[#E5E7EB] z-0" />

                <div className="relative z-10 flex flex-col items-center">
                    <div className="w-8 h-8 rounded-full bg-[#22C55E] text-white flex items-center justify-center">
                        <Check className="w-5 h-5" />
                    </div>
                    <span className="text-[12px] font-semibold text-[#16A34A] mt-2">Upload Scan</span>
                </div>

                <div className="relative z-10 flex flex-col items-center">
                    <div className="w-8 h-8 rounded-full bg-[#22C55E] text-white flex items-center justify-center">
                        <Check className="w-5 h-5" />
                    </div>
                    <span className="text-[12px] font-semibold text-[#16A34A] mt-2">AI Processing</span>
                </div>

                <div className="relative z-10 flex flex-col items-center">
                    <div className="w-8 h-8 rounded-full bg-[#135BEC] text-white flex items-center justify-center">
                        <span className="text-xs font-bold">3</span>
                    </div>
                    <span className="text-[12px] font-bold text-[#135BEC] mt-2">View Results</span>
                </div>
            </div>

            <div className="flex justify-between mb-8 px-4">
                <div>
                    <h1 className="text-[30px] font-bold">Scan Analysis Result</h1>
                    <p className="text-[14px] text-[#4C669A]">
                        Automated diagnostic report generated by AI
                    </p>
                </div>

                <Button variant="outline" asChild>
                    <Link href={'/uploadscan'} className='flex items-center gap-1.5'>
                        <ArrowLeft className="w-4 h-4" /> Back
                    </Link>
                </Button>
            </div>
            {scanData?.status === "error" && (
                <div className="text-red-500 text-center font-bold p-4 bg-red-50 rounded-xl mb-6">
                    {scanData?.message}
                </div>
            )}

            {!scan && scanData?.status !== "error" && (
                <div className="text-center text-gray-500 mt-20">
                    <p className="text-lg">No result yet...</p>
                </div>
            )}
            {scan && (
                <div className="flex flex-col lg:flex-row gap-6">

                    <div className="w-full lg:w-1/2 bg-white rounded-3xl p-4 flex items-center justify-center shadow-sm">
                        <Image
                            src={scan.imageUrl}
                            alt="Scan Image"
                            width={500}
                            height={400}
                            className="object-contain rounded-2xl"
                            priority 
                        />
                    </div>

                    {/* RIGHT: Analysis Data */}
                    <div className="w-full lg:w-1/2 flex flex-col gap-6">

                        <Card className="p-6 rounded-3xl border-none shadow-sm">
                            <div className="flex justify-between items-start mb-4">
                                <div>
                                    <h2 className="text-[22px] font-bold text-[#1E293B]">
                                        {scan.aiResult?.disease_info?.disease_name || "Unknown Condition"}
                                    </h2>
                                </div>
                                <div className="text-right">
                                    <div className="text-[28px] font-bold text-[#135BEC]">
                                        {scan.aiResult?.confidence}%
                                    </div>
                                    <span className="text-xs text-gray-500 uppercase tracking-wider font-semibold">Confidence</span>
                                </div>
                            </div>

                            <p className="text-sm text-gray-600 mb-6 leading-relaxed">
                                {scan.aiResult?.disease_info?.description}
                            </p>

                            <div>
                                <h3 className="font-bold text-[#1E293B] mb-3">Recommendations</h3>
                                <ul className="space-y-3">
                                    {scan.aiResult?.disease_info?.recommendations?.map((rec: string, i: number) => (
                                        <li key={i} className="flex gap-3 text-sm text-gray-700 items-start">
                                            <CheckCircle2 className="w-5 h-5 text-[#22C55E] shrink-0" />
                                            {rec}
                                        </li>
                                    ))}
                                </ul>
                            </div>
                        </Card>

                        <Card className="p-6 rounded-3xl border-none shadow-sm space-y-3">
                            <div className="flex justify-between text-sm">
                                <span className="text-gray-500">Scan Type:</span>
                                <span className="font-semibold">{scan.scanType}</span>
                            </div>
                            <div className="flex justify-between text-sm">
                                <span className="text-gray-500">Analysis Date:</span>
                                <span className="font-semibold">{formattedDate || "Loading..."}</span>
                            </div>
                            <div className="flex justify-between text-sm">
                                <span className="text-gray-500">Status:</span>
                                <span className="px-2 py-0.5 bg-blue-50 text-blue-600 rounded text-xs font-bold uppercase">
                                    {scan.status}
                                </span>
                            </div>
                        </Card>

                    </div>
                </div>
            )}
        </div>
    )
}
