import { Button } from '@/components/ui/button'
import { ArrowLeft, BrainCircuit, Check, CheckCircle2, Clock, Download, History, LayoutDashboard, Maximize, Maximize2, MoreVertical, RotateCw, Send, SendHorizonal, ZoomIn, ZoomOut } from 'lucide-react'
import Image from 'next/image'
import Link from 'next/link'
import React from 'react'
import MriKnee from '../../../assets/images/MRiKnee.jpg'
import { Card } from '@/components/ui/card'
export default function scanREsult() {
    return <>
        <div className="min-h-screen bg-[#F6F6F8] p-6">

            <div className="relative flex justify-between max-w-5xl mx-auto mb-16 px-4">
                <div className="absolute top-4 left-0 w-full h-0.5 bg-[#E5E7EB] z-0" />
                <div className="relative z-10 flex flex-col items-center group">
                    <div className="w-8 h-8 rounded-full bg-[#22C55E] text-white flex items-center justify-center shadow-sm">
                        <Check className="w-5 h-5" />
                    </div>
                    <span className="text-[12px] font-semibold text-[#16A34A] mt-2">Upload Scan</span>
                </div>
                <div className="relative z-10 flex flex-col items-center">
                    <div className="w-8 h-8 rounded-full bg-[#22C55E] text-white flex items-center justify-center shadow-sm">
                        <Check className="w-5 h-5" />
                    </div>
                    <span className="text-[12px] font-semibold text-[#16A34A] mt-2">AI Processing</span>
                </div>

                <div className="relative z-10 flex flex-col items-center">
                    <div className="w-8 h-8 rounded-full bg-[#135BEC] text-white flex items-center justify-center ring-4 ring-[#135bec33]">
                        <span className="text-xs font-bold">3</span>
                    </div>
                    <span className="text-[12px] font-bold text-[#135BEC] mt-2">View Results</span>
                </div>
                <div className="relative z-10 flex flex-col items-center">
                    <div className="w-8 h-8 rounded-full bg-[#E5E7EB] text-[#6B7280] flex items-center justify-center">
                        <span className="text-xs font-bold">4</span>
                    </div>
                    <span className="text-[12px] font-medium text-[#6B7280] mt-2">Doctor Review</span>
                </div>
            </div>
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 gap-4 px-4">
                <div>
                    <h1 className="text-[30px] font-bold text-[#0D121B] tracking-tight">
                        Scan Analysis Result
                    </h1>
                    <p className="text-[14px] text-[#4C669A] mt-1">
                        Automated diagnostic report generated by MedSys AI
                    </p>
                </div>

                <div className="flex gap-3">
                    <Button variant="outline" className="rounded-full border-[#E7EBF3] px-6 h-10 shadow-sm gap-2 text-[#0D121B]">
                        <Link href={'./patient-medical-history'} className='flex items-center gap-1.5'> <History className="w-4 h-4" /> History</Link>
                    </Button>
                    <Button variant="outline" className="rounded-full border-[#E7EBF3] px-6 h-10 shadow-sm gap-2 text-[#0D121B]">
                        <Link href={'./uploadscan'} className='flex items-center gap-1.5'>   <ArrowLeft className="w-4 h-4" /> Back</Link>
                    </Button>
                </div>
            </div>
            <div className="flex flex-row gap-6 items-start w-full max-w-250 ">
                {/* Left Column - Visualizer & History */}
                <div className="flex flex-col gap-6 w-full max-w-[593.33px]">
                    <div className="w-full bg-white border border-[#E7EBF3] shadow-[0px_2px_8px_rgba(0,0,0,0.05)] rounded-3xl overflow-hidden">
                        <div className="h-14.25 bg-[#F8F9FC] flex items-center justify-between px-4 border-b border-[#E7EBF3]">
                            <span className="text-[12px] font-bold text-[#4C669A] tracking-[0.6px] uppercase">
                                Visualizer
                            </span>
                            <div className="flex items-center gap-1">
                                <Button variant="ghost" size="icon" className="w-8 h-8 rounded-full text-[#4C669A]">
                                    <ZoomOut className="w-5 h-5" />
                                </Button>
                                <span className="text-[14px] font-medium text-[#0D121B] px-2">100%</span>
                                <Button variant="ghost" size="icon" className="w-8 h-8 rounded-full text-[#4C669A]">
                                    <ZoomIn className="w-5 h-5" />
                                </Button>
                                <div className="w-px h-4 bg-[#E7EBF3] mx-1" />
                                <Button variant="ghost" size="icon" className="w-8 h-8 rounded-full text-[#4C669A]">
                                    <RotateCw className="w-5 h-5" />
                                </Button>
                                <Button variant="ghost" size="icon" className="w-8 h-8 rounded-full text-[#4C669A]">
                                    <Maximize className="w-5 h-5" />
                                </Button>
                            </div>
                        </div>

                        <div className="p-4 bg-white">
                            <div className="relative w-full bg-[#E5E7EB] rounded-lg overflow-hidden group">
                                <div className="flex items-center justify-center">
                                    <Image
                                        src={MriKnee}
                                        alt='MriKnee'
                                        className="w-full h-auto object-contain"
                                        priority
                                    />
                                </div>
                            </div>
                        </div>

                        <div className="h-11.25 bg-white border-t border-[#E7EBF3] flex items-center justify-between px-4">
                            <div className="text-[14px] text-[#4C669A]">
                                View: <span className="font-medium">Anterior-Posterior (AP)</span>
                            </div>
                            <div className="flex items-center gap-6">
                                <div className="flex items-center gap-2">
                                    <div className="w-2 h-2 bg-[#135BEC] rounded-full ring-2 ring-blue-100" />
                                    <span className="text-[14px] font-medium text-[#0D121B]">AI Anomaly</span>
                                </div>
                                <div className="flex items-center gap-2">
                                    <div className="w-2 h-2 bg-[#D1D5DB] rounded-full" />
                                    <span className="text-[14px] text-[#4C669A]">Normal Tissue</span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <Card className="w-[593.33px] h-60 bg-white border border-[#E7EBF3] rounded-[24px] shadow-sm relative overflow-hidden p-0">
                        <div className="flex justify-between items-center px-5 pt-5 pb-4">
                            <div className="flex items-center gap-2">
                                <History className="w-6 h-7 text-[#135BEC]" />
                                <h3 className="font-bold text-[16px] leading-6 text-[#0D121B]">
                                    Patient Scan History
                                </h3>
                            </div>
                            <button className="text-[#135BEC] font-medium text-[14px] leading-5 hover:underline">
                                <Link href={'./patient-medical-history'}>View All</Link>
                            </button>
                        </div>

                        <div className="flex gap-4 px-5 overflow-x-auto pb-4">
                            <div className="min-w-40 w-40 bg-[#F8F9FC] border border-[#E7EBF3] rounded-3xl p-3 flex flex-col group transition-all hover:border-[#135BEC]">
                                <div className="w-full h-20 bg-[#E5E7EB] rounded-[6px] overflow-hidden mb-2 relative flex items-center justify-center">
                                    <Image src={MriKnee} alt='mriknee' className="object-cover" />
                                </div>
                                <span className="text-[14px] font-semibold leading-5 text-[#0D121B]">Chest X-Ray</span>
                                <span className="text-[12px] leading-4 text-[#4C669A]">Jan 12, 2023</span>
                            </div>

                            <div className="min-w-40 w-40 bg-[#F8F9FC] border border-[#E7EBF3] rounded-3xl p-3 flex flex-col group transition-all hover:border-[#135BEC]">
                                <div className="w-full h-20 bg-[#E5E7EB] rounded-[6px] overflow-hidden mb-2 relative flex items-center justify-center">
                                    <Image src={MriKnee} alt='mriknee' className="object-cover" />
                                </div>
                                <span className="text-[14px] font-semibold leading-5 text-[#0D121B]">Right Knee MRI</span>
                                <span className="text-[12px] leading-4 text-[#4C669A]">Nov 05, 2022</span>
                            </div>
                        </div>
                    </Card>
                </div>

                {/* Right Column - AI Analysis Sidebar */}
                <div className="flex flex-col gap-6 w-95 shrink-0">
                    <Card className="w-full h-139.25 bg-white border border-[#E7EBF3] shadow-[0px_2px_12px_rgba(0,0,0,0.08)] rounded-3xl p-6 flex flex-col overflow-hidden">
                        <div className="flex justify-between items-start mb-6">
                            <div className="flex flex-col gap-3">
                                <div className="flex items-center gap-2 bg-[#F0FDF4] px-3 py-1 rounded-full w-fit">
                                    <div className="w-1.5 h-1.5 bg-[#22C55E] rounded-full" />
                                    <span className="text-[10px] font-bold text-[#15803D] uppercase tracking-wider">Analysis Completed</span>
                                </div>
                                <h2 className="text-[24px] font-bold text-[#0D121B] leading-[30px]">Hairline Fracture<br />(Tibia)</h2>
                            </div>
                            <div className="text-right">
                                <div className="text-[30px] font-bold text-[#135BEC] leading-none">94%</div>
                                <div className="text-[10px] font-bold text-[#4C669A] uppercase tracking-widest mt-1">Confidence</div>
                            </div>
                        </div>
                        <div className="mb-6">
                            <div className="flex justify-between items-center mb-2">
                                <span className="text-[14px] font-semibold text-[#0D121B]">Risk Level</span>
                                <span className="text-[14px] font-bold text-[#DC2626]">High Risk</span>
                            </div>
                            <div className="relative h-2 w-full bg-[#F3F4F6] rounded-full overflow-hidden">
                                <div className="absolute inset-0 bg-linear-to-r from-[#4ADE80] via-[#FACC15] to-[#EF4444]" />
                            </div>
                        </div>
                        <div className="bg-[#F8F9FC] border border-[#E7EBF3] rounded-[24px] p-4 mb-6 flex-1 overflow-y-auto">
                            <div className="flex items-center gap-2 mb-2">
                                <BrainCircuit className="w-5 h-5 text-[#135BEC] shrink-0" />
                                <h3 className="text-[14px] font-bold text-[#0D121B]">AI Explanation Summary</h3>
                            </div>
                            <p className="text-[13px] text-[#4C669A] leading-5">
                                The AI model detected a discontinuity in the cortical bone of the left tibia upper shaft.
                                The pattern is consistent with a hairline fracture. Mild soft tissue swelling is observed.
                            </p>
                        </div>
                        <div className="shrink-0">
                            <h3 className="text-[14px] font-bold text-[#0D121B] mb-3">AI Suggested Next Steps</h3>
                            <ul className="space-y-3">
                                <li className="flex items-start gap-3">
                                    <CheckCircle2 className="w-4 h-4 text-[#135BEC] mt-0.5 shrink-0" />
                                    <span className="text-[13px] text-[#4C669A]">Immediate immobilization (Cast/Brace)</span>
                                </li>
                                <li className="flex items-start gap-3">
                                    <CheckCircle2 className="w-4 h-4 text-[#135BEC] mt-0.5 shrink-0" />
                                    <span className="text-[13px] text-[#4C669A]">Referral to orthopedic surgery</span>
                                </li>
                            </ul>
                        </div>
                    </Card>

                    <Card className="w-full h-125.5 bg-white border border-[#E7EBF3] shadow-[0px_2px_8px_rgba(0,0,0,0.05)] rounded-3xl p-6 flex flex-col overflow-hidden">
                        <div className="bg-[#EFF6FF] border border-[#DBEAFE] rounded-[24px] p-4 flex items-center gap-4 mb-6">
                            <div className="w-10 h-10 bg-white border border-[#DBEAFE] rounded-full flex items-center justify-center shrink-0 shadow-sm">
                                <span className="text-[18px] font-bold text-[#135BEC]">JD</span>
                            </div>
                            <div>
                                <h4 className="text-[14px] font-bold text-[#0D121B]">John Doe</h4>
                                <p className="text-[11px] text-[#4C669A] leading-4">Male, 45 Years • ID: #P-8832<br />DOB: 12/04/1978</p>
                            </div>
                        </div>

                        <div className="grid grid-cols-2 gap-y-6 py-6 border-y border-[#E7EBF3] mb-auto">
                            <div>
                                <p className="text-[10px] font-bold text-[#4C669A] uppercase tracking-wider mb-1">Scan Type</p>
                                <p className="text-[14px] font-semibold text-[#0D121B]">X-Ray (Tibia)</p>
                            </div>
                            <div>
                                <p className="text-[10px] font-bold text-[#4C669A] uppercase tracking-wider mb-1">Scan Date</p>
                                <p className="text-[14px] font-semibold text-[#0D121B]">Oct 24, 2023</p>
                            </div>
                            <div>
                                <p className="text-[10px] font-bold text-[#4C669A] uppercase tracking-wider mb-1">Doctor Status</p>
                                <div className="bg-[#FEF9C3] px-2 py-0.5 rounded-xl w-fit">
                                    <span className="text-[11px] font-medium text-[#854D0E]">Pending Review</span>
                                </div>
                            </div>
                            <div>
                                <p className="text-[10px] font-bold text-[#4C669A] uppercase tracking-wider mb-1">Scan ID</p>
                                <p className="text-[13px] text-[#0D121B]">#SCN-9201</p>
                            </div>
                        </div>

                        <div className="flex flex-col gap-3 mt-6">
                            <Button className="h-12.5 flex items-center gap-1.5 bg-[#135BEC] text-white rounded-[24px] text-[15px] font-bold shadow-md"><Download className='font-bold mr-5' />  Download Report</Button>
                            <Button variant="outline" className="h-12.5 flex items-center gap-2 border-[#E7EBF3] rounded-[24px] text-[15px] font-bold">
                                <SendHorizonal className='font-bold mr-5' />
                                Send to Doctor</Button>
                            <p className="text-[10px] font-bold text-[#9CA3AF] text-center leading-4 pt-2">Medical Disclaimer: This analysis is generated by AI for
                                assistive purposes only. It does not replace professional
                                medical diagnosis. Please consult a specialist.</p>
                        </div>
                    </Card>
                </div>


            </div>



        </div>
    </>
}
